param(
  [Parameter(Mandatory = $true)]
  [string]$ResultsCsv,

  [string]$ReportPath = (Join-Path $PSScriptRoot "..\\report_c#.tex")
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $ResultsCsv)) {
  throw "Results CSV not found: $ResultsCsv"
}
if (-not (Test-Path $ReportPath)) {
  throw "Report not found: $ReportPath"
}

$rows = Import-Csv $ResultsCsv
if (-not $rows -or $rows.Count -eq 0) {
  throw "Results CSV is empty: $ResultsCsv"
}

# Build lookup: dataset -> points -> total_s
$map = @{}
foreach ($r in $rows) {
  $ds = [string]$r.dataset
  $p = [int]$r.points
  $t = [double]$r.total_s
  if (-not $map.ContainsKey($ds)) { $map[$ds] = @{} }
  $map[$ds][$p] = $t
}

$datasets = @(
  @{ key = "small_city_block"; prefix = "CsSmall"  },
  @{ key = "medium_district";  prefix = "CsMedium" },
  @{ key = "large_metro";      prefix = "CsLarge"  }
)

function Fmt-Time([double]$t) {
  return [string]::Format([System.Globalization.CultureInfo]::InvariantCulture, "{0:0.00}", $t)
}

function Fmt-Speedup([double]$s) {
  $n = [string]::Format([System.Globalization.CultureInfo]::InvariantCulture, "{0:0.00}", $s)
  return ($n + '$\times$')
}

$genAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
$genFrom = (Resolve-Path $ResultsCsv).Path

$blockLines = @()
$blockLines += "% AUTO-GENERATED RESULTS START"
$blockLines += "% Generated by: gcp/update_report_csharp.ps1"
$blockLines += "% Generated at: $genAt"
$blockLines += "% Source CSV: $genFrom"

foreach ($d in $datasets) {
  $key = $d.key
  $prefix = $d.prefix

  if (-not $map.ContainsKey($key)) {
    throw "Dataset '$key' not found in CSV. Present datasets: $(@($map.Keys) -join ', ')"
  }

  $pt = $map[$key]
  foreach ($p in @(1,4,7)) {
    if (-not $pt.ContainsKey($p)) {
      throw "Missing points=$p for dataset '$key' in CSV."
    }
  }

  $t1 = [double]$pt[1]
  $t4 = [double]$pt[4]
  $t7 = [double]$pt[7]

  if ($t4 -le 0 -or $t7 -le 0) {
    throw "Non-positive timing in CSV for dataset '$key' (t4=$t4, t7=$t7)."
  }

  $s4 = $t1 / $t4
  $s7 = $t1 / $t7
  $smax = [Math]::Max($s4, $s7)

  $blockLines += "\newcommand{\$($prefix)TOne}{$(Fmt-Time $t1)}"
  $blockLines += "\newcommand{\$($prefix)TFour}{$(Fmt-Time $t4)}"
  $blockLines += "\newcommand{\$($prefix)TSeven}{$(Fmt-Time $t7)}"
  $blockLines += "\newcommand{\$($prefix)SMax}{$(Fmt-Speedup $smax)}"
}

$blockLines += "% AUTO-GENERATED RESULTS END"
$block = ($blockLines -join "`r`n")

$content = Get-Content $ReportPath -Raw
$pattern = "(?s)% AUTO-GENERATED RESULTS START.*?% AUTO-GENERATED RESULTS END"

if (-not ([System.Text.RegularExpressions.Regex]::IsMatch($content, $pattern))) {
  throw "Could not find auto-generated block markers in report. Expected markers: '% AUTO-GENERATED RESULTS START' and '% AUTO-GENERATED RESULTS END'."
}

# Backup before patching
$backupPath = ($ReportPath + ".bak_" + (Get-Date).ToString("yyyyMMdd_HHmmss"))
Copy-Item -Force $ReportPath $backupPath | Out-Null

$regex = New-Object System.Text.RegularExpressions.Regex($pattern)
$newContent = $regex.Replace($content, { param($m) $block })

$reportFullPath = (Resolve-Path $ReportPath).Path
[System.IO.File]::WriteAllText($reportFullPath, $newContent, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Updated report: $ReportPath"
Write-Host "Backup saved:  $backupPath"

